function:
  name: omni-live-mark-as-delivered-${self:provider.stage}
  handler: src/mark-as-delivered.lambda_handler
  description: omni live logistics mark-as-delivered
  timeout: 900
  package:
    patterns:
      - "!**/*"
      - "src/shared/**"
      - "src/mark-as-delivered.py"
      - "src/query_file.sql"
  runtime: python3.11
  layers:
      - arn:aws:lambda:us-east-1:332281781429:layer:requests:1
      - arn:aws:lambda:us-east-1:332281781429:layer:urllib:1
      - arn:aws:lambda:us-east-1:332281781429:layer:pytz:1
  environment:
      # Dynamo_Table: !Ref ReadyforBilling
      Environment: ${self:provider.stage}
      Username: ${ssm:/readytobill/lvlp/username/${self:provider.stage}}
      Password: ${ssm:/readytobill/lvlp/password/${self:provider.stage}}
